import os

HAMILTON_ENERGY_UN = os.environ.get('HAMILTON_ENERGY_UN')
HAMILTON_ENERGY_PW = os.environ.get('HAMILTON_ENERGY_PW')

NEST_USERNAME = os.environ.get("NEST_USERNAME")
NEST_PASSWORD = os.environ.get("NEST_PASSWORD")

USGS_SITE = "04108660"

WUNDERGROUND_API_KEY = os.environ.get('WUNDERGROUND_API_KEY')
WUNDERGROUND_STATION_ID = "KMIFENNV2"

